name: auto-update

on:
  workflow_dispatch:

jobs:
  updates:
    uses: memo33/sc4pac-actions/.github/workflows/sc4pac-channel-updates.yaml@check-updates
    with:
      path: src/yaml
      api: sc4e  # sc4e,stex
      deploy-repository: memo33/sc4pac-test-channel
    secrets:
      stex-api-key: ${{ secrets.STEX_API_KEY }}
      pat: ${{ secrets.SC4PAC_CHECK_UPDATES_TOKEN }}
    permissions:
      pull-requests: write
