name: sc4pac CI

on:
  push:
    branches: [ "main", "action" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  channel:
    uses: memo33/sc4pac-actions/.github/workflows/sc4pac-channel.yaml@unstable
    with:
      path: src/yaml
      channel-label: Test
      deploy-repository: memo33/sc4pac-test-channel
      # sc4pac-tools-submodule: sc4pac-tools
      use-stex-api: true
    secrets:
      stex-api-key: ${{ secrets.STEX_API_KEY }}
      sc4pac-simtropolis-token: ${{ secrets.SC4PAC_SIMTROPOLIS_TOKEN }}
    permissions:
      pages: write
      id-token: write
