name: sc4pac CI/CD

on:
  push:
    branches: [ "main", "action" ]
  pull_request_target:
    branches: [ "main" ]
  workflow_dispatch:  # for manually triggering the workflow from Actions tab

jobs:
  lint-deploy:
    uses: memo33/sc4pac-actions/.github/workflows/sc4pac.yaml@main
    with:
      path: src/yaml
      deploy-repository: 'memo33/sc4pac-test-channel'
    permissions:
      pages: write
      id-token: write
