name: sc4pac CI/CD

on:
  push:
    branches: [ "main", "action" ]
  pull_request_target:
    branches: [ "main" ]


jobs:
  channel:
    uses: memo33/sc4pac-actions/.github/workflows/sc4pac.yaml@main
    with:
      path: src/yaml
      deploy-repository: memo33/sc4pac-test-channel
      sc4pac-tools-submodule: sc4pac-tools
    permissions:
      pages: write
      id-token: write
